# Generated by Django 5.0.6 on 2024-05-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Створено'), (1, 'Сплачено'), (2, 'В дорозі'), (3, 'Доставлено')], default=0),
        ),
    ]
